name: CI

on: [push, workflow_dispatch]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Protoc
      run: |
        sudo apt update
        sudo apt-get install protobuf-compiler -y

    - name: Cargo Test
      env:
        SA: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        echo $SA > clientsecret.json
        cargo test

    - name: Clippy
      run: cargo clippy --all-features -- --deny warnings
